services:
  app:
    build:
      context: .
      dockerfile: my-app/Dockerfile
    container_name: cosmjs-vite-app
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
      - /app/node_modules
